[project]
name = "data-engineering-pracitce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "delta-spark>=4.2.0",
    "fastapi<0.136",
    "httpx<0.29",
    "mypy>=2.1.0",
    "pandas>=3.0.3",
    "pyspark>=4.1.1",
    "pytest>=9.0.3",
    "ruff>=0.15.13",
]
